# Generated by Django 2.1.1 on 2018-10-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'calcium',
            },
        ),
        migrations.CreateModel(
            name='Phosphorus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'phosphorus',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sugar',
            },
        ),
        migrations.CreateModel(
            name='VitaminA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vitaminA',
            },
        ),
        migrations.CreateModel(
            name='VitaminB12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vitaminB12',
            },
        ),
        migrations.CreateModel(
            name='VitaminB6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vitaminB6',
            },
        ),
        migrations.CreateModel(
            name='VitaminC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vitaminC',
            },
        ),
        migrations.CreateModel(
            name='VitaminD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=10)),
                ('female', models.CharField(max_length=10)),
                ('pregnancy', models.CharField(max_length=10)),
                ('lactation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vitaminD',
            },
        ),
    ]
